[package]
name = "beek"
version = "0.1.0"
authors = ["mosm <airman515@gmail.com>"]
edition = "2018"

[dependencies]
colored = "2.0.0"
combine = "4.2.1"
itertools = "0.9.0"
statrs = "0.13.0"
thiserror = "1.0.20"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rustyline = "6.2.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
wasm-bindgen = "0.2.67"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "beek-bin"
path = "src/main.rs"
doc = false

[profile.release]
lto = true
