name: deploy

on:
    workflow_dispatch:
    workflow_run:
        workflows: [build]
        branches: [master]
        types: [completed]

jobs:
    deploy:
        runs-on: ubuntu-20.04
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            - uses: actions/checkout@v2
            - uses: hecrj/setup-rust-action@v1
              with:
                  targets: wasm32-unknown-unknown
            - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
            - run: npm ci
            - run: npm run build
            - uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./public
                  enable_jekyll: false
                  commit_message: ${{ github.event.head_commit.message }}
                  force_orphan: true
